#!/usr/bin/env bash
# backups to my DB

CURR_DATE=$(date +'%d-%m-%Y')
file_name="${CURR_DATE}.tar.gz"
mysqldump --all-databases -u root --password="$1" > backup.sql
tar -czvf "$file_name" backup.sql

