#!/usr/bin/env bash
#Creates a file, displays text, signals and terminates itself
echo $$ > /var/run/myscript.pid
trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command' &&& rm -f /var/run/myscript.pid; exit" SIGTERM SIGQUIT
while :
do
	echo 'To inifinity and beyond'
	sleep 2
done
