#!/usr/bin/env bash
#Display Best School for 9 times and Hi on the last
i=0
while [ $i -lt 10 ]; do
	if [ $i -eq 8 ]; then
		echo 'Best School'
		echo 'Hi'
	else
		echo 'Best School'
	fi
	((i++))
done
