#!/usr/bin/env bash
# Run Nginx as user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/listen\s*80;/listen 8080;/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
